export const LOAD_ACCOUNT = 'stellar/LOAD_ACCOUNT';
export const LOAD_ACCOUNT_SUCCESS = 'stellar/LOAD_ACCOUNT_SUCCESS';
export const LOAD_ACCOUNT_ERROR = 'stellar/LOAD_ACCOUNT_ERROR';
export const LOAD_PAYMENTS_SUCCESS = 'stellar/LOAD_PAYMENTS_SUCCESS';
